#!/usr/bin/env php

<?php

require __DIR__.'/vendor/autoload.php';

use JBZoo\Utils\Ser;

if (count($argv) <= 1 || count($argv) >= 5) {
    // usage
    echo <<<EOF

          __  .__
  _______/  |_|__| ____   _____ _____
 /  ___/\   __\  |/ ___\ /     \\\__  \
 \___ \  |  | |  / /_/  >  Y Y  \/ __ \_
/____  > |__| |__\___  /|__|_|  (____  /
     \/         /_____/       \/     \/

Usage:
  php stigma <database_file_path> <target> <replace>

Example:
  php stigma ./ht.sqlite localhost 160.122.111.11

EOF;
    exit(1);
} else {
    @list(, $database_file_path, $target, $replace) = $argv;
}

$app = new Hikouki\Stigma\App;

$app->execute();
